import type { ReviewedGreenhouseSource } from './greenhouse-config.js';

/**
 * API-probed boards admitted for the owner's single-user rollout on
 * 2026-07-29T21:07:31.798Z. Display names are the current Greenhouse board
 * identities, not inferred discovery labels. These entries are intentionally
 * published before first-party ownership review and remain fail-closed at the
 * board, schema, and application-host boundaries.
 */
const apiProbedBoards: Array<{
  token: string;
  name: string;
  boardName?: string;
  admittedAt?: string;
  initialHosts: string[];
  finalHosts: string[];
}> = [
  { token: "ada18", name: "Ada", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "aevexaerospace", name: "AEVEX", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "airbnb", name: "Airbnb", initialHosts: ["careers.airbnb.com"], finalHosts: ["careers.airbnb.com"] },
  { token: "algolia", name: "Algolia", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "alphagrepsecurities", name: "AlphaGrep Securities", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "amarok", name: "AMAROK", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "amplitude", name: "Amplitude", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "andurilindustries", name: "Anduril Industries", initialHosts: ["boards.greenhouse.io"], finalHosts: ["boards.greenhouse.io","job-boards.greenhouse.io"] },
  { token: "anthropic", name: "Anthropic", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "aperaaiinc", name: "Apera AI Inc", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "appian", name: "Appian Corporation", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "appier", name: "Appier", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "apptronik", name: "Apptronik", initialHosts: ["boards.greenhouse.io"], finalHosts: ["boards.greenhouse.io","job-boards.greenhouse.io"] },
  { token: "aquaticcapitalmanagement", name: "Aquatic Capital Management", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "argmax", name: "Argmax", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "artefactlinkedin", name: "LinkedIn Job Wrapping", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "asteraearlycareer2026", name: "Astera Labs Early Career", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "astranis", name: "Astranis", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "auctane", name: "Auctane", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "axiomaticai", name: "Axiomatic_AI", initialHosts: ["job-boards.eu.greenhouse.io"], finalHosts: ["job-boards.eu.greenhouse.io"] },
  { token: "axontalentcommunity", name: "Join Our Talent Community", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "billiontoone", name: "BillionToOne", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "bird", name: "Bird", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "botauto", name: "Bot Auto", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "brex", name: "Brex", initialHosts: ["www.brex.com"], finalHosts: ["www.brex.com"] },
  { token: "celonis", name: "Celonis", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "checkr", name: "Checkr", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "clarityinnovates", name: "Clarity Innovations", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "clever", name: "Clever", initialHosts: ["www.clever.com"], finalHosts: ["www.clever.com"] },
  { token: "clockworksystems", name: "Clockwork.io", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "coinbase", name: "Coinbase", initialHosts: ["www.coinbase.com"], finalHosts: ["www.coinbase.com"] },
  { token: "cresta", name: "Cresta", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "ctccampusboard", name: "CTC Campus - External, Not Advertised", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "databricks", name: "Databricks", initialHosts: ["databricks.com"], finalHosts: ["databricks.com"] },
  { token: "diligentcorporation", name: "Diligent Corporation", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "docugami", name: "Docugami", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "doubleverify", name: "DoubleVerify", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "dropbox", name: "Dropbox", initialHosts: ["jobs.dropbox.com","www.dropbox.jobs"], finalHosts: ["jobs.dropbox.com","www.dropbox.jobs"] },
  { token: "drweng", name: "DRW", initialHosts: ["job-boards.greenhouse.io","drw.com"], finalHosts: ["job-boards.greenhouse.io","drw.com"] },
  { token: "engineersgate", name: "Engineers Gate", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "enova", name: "Enova International", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "eulerity", name: "Eulerity", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "evolver", name: "Evolver", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "excelsportsmanagement", name: "Excel Sports Management", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "faire", name: "Faire", initialHosts: ["boards.greenhouse.io"], finalHosts: ["boards.greenhouse.io","job-boards.greenhouse.io"] },
  { token: "faradayfuture", name: "Faraday Future", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "figureai", name: "Figure", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "financialtimes33", name: "Financial Times", initialHosts: ["job-boards.eu.greenhouse.io"], finalHosts: ["job-boards.eu.greenhouse.io"] },
  { token: "fiveringsllc", name: "Five Rings LLC - Careers", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "fivetran", name: "Fivetran", initialHosts: ["www.fivetran.com"], finalHosts: ["www.fivetran.com"] },
  { token: "flagshippioneeringinc", name: "Flagship Pioneering, Inc.", initialHosts: ["boards.greenhouse.io"], finalHosts: ["boards.greenhouse.io","job-boards.greenhouse.io"] },
  { token: "flexport", name: "Flexport", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "flowtraders", name: "Flow Traders", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "fourhands", name: "Four Hands", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "freeformfuturecorp", name: "Freeform", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "fspco-op012325", name: "Flagship Pioneering Co-Op Program", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "gardacp", name: "Garda Capital Partners", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "gemini", name: "Gemini", initialHosts: ["boards.greenhouse.io"], finalHosts: ["boards.greenhouse.io","job-boards.greenhouse.io"] },
  { token: "genscript", name: "GenScript/ProBio", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "ginkgobioworks", name: "Ginkgo Bioworks Inc.", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "gitlab", name: "GitLab", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "gleanwork", name: "Glean", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "goalhonduras", name: "GOAL Honduras", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "goatgroup", name: "GOAT Group", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "gotion", name: "Gotion, Inc.", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "groww", name: "Groww", initialHosts: ["job-boards.eu.greenhouse.io"], finalHosts: ["job-boards.eu.greenhouse.io"] },
  { token: "gusto", name: "Gusto, Inc.", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "honehealth", name: "Hone Health", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "horizonindustrieslimited", name: "Horizon Industries", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "icml", name: "Optiver - ICML", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "imc", name: "IMC", initialHosts: ["job-boards.eu.greenhouse.io"], finalHosts: ["job-boards.eu.greenhouse.io"] },
  { token: "instacart", name: "Instacart", initialHosts: ["instacart.careers"], finalHosts: ["instacart.careers"] },
  { token: "instead", name: "Instead", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "integra", name: "Integra FEC", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "intrinsicrobotics", name: "Intrinsic", initialHosts: ["boards.greenhouse.io"], finalHosts: ["boards.greenhouse.io","job-boards.greenhouse.io"] },
  { token: "ispottv", name: "iSpot", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "janestreet", name: "Jane Street", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "jobsatphamily", name: "Phamily", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "jumptrading", name: "Jump Trading", initialHosts: ["www.jumptrading.com"], finalHosts: ["www.jumptrading.com"] },
  { token: "kensingtontours", name: "Kensington", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "later", name: "Later", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "liberate", name: "Liberate", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "lilasciences", name: "Lila Sciences", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "liveviewtechnologiesinc", name: "LVT", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "lucidmotors", name: "Lucid Motors", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "mixpanel", name: "Mixpanel", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "moloco", name: "Moloco", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "momentenergy", name: "Moment Energy", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "momentus", name: "Momentus Space LLC", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "mongodb", name: "MongoDB", initialHosts: ["www.mongodb.com"], finalHosts: ["www.mongodb.com"] },
  { token: "msfcareers", name: "Medecins Sans Frontieres (Doctors Without Borders) - United States", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "neuralink", name: "Neuralink", initialHosts: ["boards.greenhouse.io"], finalHosts: ["boards.greenhouse.io","job-boards.greenhouse.io"] },
  { token: "newsbreak", name: "NewsBreak", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "nirmata", name: "Nirmata", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "odeko", name: "Odeko", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "offerup", name: "OfferUp", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "oklo", name: "Oklo", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "oneethos", name: "OneEthos", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "onenergy", name: "ON.energy", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "optiver", name: "Optiver", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "optiverneurips", name: "Optiver - NeurIPS", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "optiverprivate", name: "Optiver Private Jobs", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "orennia", name: "Orennia", initialHosts: ["boards.greenhouse.io"], finalHosts: ["boards.greenhouse.io","job-boards.greenhouse.io"] },
  { token: "pagerduty", name: "PagerDuty", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "pdtpartners", name: "PDT Partners", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "perscholashires", name: "Per Scholas", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "pinterest", name: "Pinterest", initialHosts: ["www.pinterestcareers.com"], finalHosts: ["www.pinterestcareers.com"] },
  { token: "point72", name: "Point72", initialHosts: ["boards.greenhouse.io"], finalHosts: ["boards.greenhouse.io","job-boards.greenhouse.io"] },
  { token: "pointc", name: "Point C", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "purestorage", name: "Everpure", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "queracomputinginc", name: "QuEra Computing, Inc.", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "radixuniversity", name: "Radix Trading University Job Board", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "reddit", name: "Reddit", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "rendezvousrobotics", name: "Rendezvous Robotics", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "rise8", name: "Rise8", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "roblox", name: "Roblox", initialHosts: ["careers.roblox.com"], finalHosts: ["careers.roblox.com"] },
  { token: "rocketlab", name: "Rocket Lab Corporation", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "safariai", name: "Safari AI", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "samayaai", name: "Samaya AI", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "samsungresearchamericainternship", name: "Samsung Research America Internship", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "scaleai", name: "Scale AI", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "schonfeld", name: "Schonfeld", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "scm", name: "Stevens Capital Management LP", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "scopely", name: "Scopely", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "sevenresearch", name: "Seven Research", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "sharkninjaoperatingllc", name: "SharkNinja", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "shifttechnology", name: "Shift Technology", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "smartasset", name: "SmartAsset", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "spacex", name: "SpaceX", initialHosts: ["boards.greenhouse.io"], finalHosts: ["boards.greenhouse.io","job-boards.greenhouse.io"] },
  { token: "squarepointcapital", name: "Squarepoint Capital", initialHosts: ["www.squarepoint-capital.com"], finalHosts: ["www.squarepoint-capital.com"] },
  { token: "stackadapt-confidential", name: "StackAdapt - Confidential", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "stripe", name: "Stripe", initialHosts: ["stripe.com"], finalHosts: ["stripe.com"] },
  { token: "studiokraftonboard", name: "KRAFTON Montréal Studio", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "submittable", name: "Submittable", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "talentprograms", name: "Hunter Douglas - Talent Programs", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "tenstorrentuniversity", name: "Tenstorrent University Jobs", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "thetradedesk", name: "The Trade Desk", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "togetherai", name: "Together AI", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "torcrobotics", name: "Torc Robotics", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "toshibaglobalcommercesolutions", name: "Toshiba Global Commerce Solutions - External", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "transmarketgroup", name: "TransMarket Group", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "tribalscale", name: "TribalScale", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "trueanomalyinc", name: "True Anomaly", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "truebill", name: "Rocket Money", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "truveta", name: "Truveta", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "twitch", name: "Twitch", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "twosixtechnologies", name: "Two Six Technologies", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "vardaspace", name: "Varda Space Industries", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "vast", name: "Vast", initialHosts: ["boards.greenhouse.io"], finalHosts: ["boards.greenhouse.io","job-boards.greenhouse.io"] },
  { token: "veeamsoftware", name: "Veeam Software", initialHosts: ["job-boards.eu.greenhouse.io"], finalHosts: ["job-boards.eu.greenhouse.io"] },
  { token: "verkada", name: "Verkada", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "virtu", name: "Virtu Financial", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "virturecruitinghidden", name: "Virtu Careers", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "voloridgeinvestmentmanagement", name: "Voloridge Investment Management", initialHosts: ["voloridge.com"], finalHosts: ["voloridge.com"] },
  { token: "walleyecapital-external-students", name: "Walleye Capital Internships", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "weave", name: "Weave", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "webflow", name: "Webflow", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "worldquant", name: "WorldQuant", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "xometry", name: "Xometry", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  { token: "xpengmotors", name: "XPENG", initialHosts: ["job-boards.greenhouse.io"], finalHosts: ["job-boards.greenhouse.io"] },
  // #231 posting-identity remediation batch 1 (2026-09-29). These boards were
  // probed against the public Greenhouse identity endpoint; every board name
  // below is the name the API returns, and each rejected/again-closed posting
  // keeps its provenance until retention or a reviewed lifecycle decision.
  // Admitting the official board is the collision-safe anchor for the reviewed
  // custom-host application routes the community lists already use
  // (`customGreenhouseReference` in `src/identity/posting.ts`), so an exact
  // provider route can resolve against that board's active checkpoint.
  { token: "akunacapital", name: "Akuna Capital", admittedAt: "2026-09-29T15:38:36.000Z", initialHosts: ["akunacapital.com"], finalHosts: ["akunacapital.com"] },
  { token: "duolingo", name: "Duolingo", admittedAt: "2026-09-29T15:38:36.000Z", initialHosts: ["careers.duolingo.com"], finalHosts: ["careers.duolingo.com"] },
  { token: "epicgames", name: "Epic Games", admittedAt: "2026-09-29T15:38:36.000Z", initialHosts: ["epicgames.com"], finalHosts: ["epicgames.com"] },
  { token: "flyzipline", name: "Zipline", admittedAt: "2026-09-29T15:38:36.000Z", initialHosts: ["zipline.com"], finalHosts: ["zipline.com"] },
  { token: "oldmissioncapital", name: "Old Mission Capital", boardName: "Old Mission", admittedAt: "2026-09-29T15:38:36.000Z", initialHosts: ["oldmissioncapital.com"], finalHosts: ["oldmissioncapital.com"] },
  { token: "pathai", name: "PathAI", admittedAt: "2026-09-29T15:38:36.000Z", initialHosts: ["pathai.com"], finalHosts: ["pathai.com"] },
  { token: "rubrik", name: "Rubrik Job Board", admittedAt: "2026-09-29T15:38:36.000Z", initialHosts: ["rubrik.com"], finalHosts: ["rubrik.com"] },
  { token: "samsara", name: "Samsara", admittedAt: "2026-09-29T15:38:36.000Z", initialHosts: ["samsara.com"], finalHosts: ["samsara.com"] },
  { token: "towerresearchcapital", name: "Tower Research Capital", admittedAt: "2026-09-29T15:38:36.000Z", initialHosts: ["tower-research.com"], finalHosts: ["tower-research.com"] },
  { token: "waymo", name: "Waymo", admittedAt: "2026-09-29T15:38:36.000Z", initialHosts: ["withwaymo.com"], finalHosts: ["withwaymo.com"] },
  { token: "wehrtyou", name: "Hudson River Trading", admittedAt: "2026-09-29T15:38:36.000Z", initialHosts: ["hudsonrivertrading.com"], finalHosts: ["hudsonrivertrading.com"] },
  // #231 posting-identity remediation batch 2 (2026-09-29). Same probe rule as
  // batch 1: the board name is the value the public identity endpoint returns,
  // and each host is the apex of the board's own application URLs. Lyft's
  // Greenhouse board presents through CareerPuck, so its reviewed route is the
  // `/job-board/{board}/job/{id}` form handled in `reviewed-provider.ts`.
  { token: "aqr", name: "AQR", admittedAt: "2026-09-29T16:46:00.000Z", initialHosts: ["aqr.com"], finalHosts: ["aqr.com"] },
  { token: "asm", name: "ASM", admittedAt: "2026-09-29T16:46:00.000Z", initialHosts: ["asm.com"], finalHosts: ["asm.com"] },
  { token: "awardco", name: "Awardco", admittedAt: "2026-09-29T16:46:00.000Z", initialHosts: ["award.co"], finalHosts: ["award.co"] },
  { token: "formlabs", name: "Formlabs", admittedAt: "2026-09-29T16:46:00.000Z", initialHosts: ["formlabs.com"], finalHosts: ["formlabs.com"] },
  { token: "healthesystems", name: "Healthesystems", admittedAt: "2026-09-29T16:46:00.000Z", initialHosts: ["healthesystems.com"], finalHosts: ["healthesystems.com"] },
  { token: "helsing", name: "Helsing", admittedAt: "2026-09-29T16:46:00.000Z", initialHosts: ["helsing.ai"], finalHosts: ["helsing.ai"] },
  { token: "interstates", name: "Interstates", admittedAt: "2026-09-29T16:46:00.000Z", initialHosts: ["interstates.com"], finalHosts: ["interstates.com"] },
  { token: "kinexon", name: "KINEXON", admittedAt: "2026-09-29T16:46:00.000Z", initialHosts: ["kinexon.com"], finalHosts: ["kinexon.com"] },
  { token: "lyft", name: "Lyft", admittedAt: "2026-09-29T16:46:00.000Z", initialHosts: ["careerpuck.com"], finalHosts: ["careerpuck.com"] },
  { token: "payoneer", name: "Payoneer", admittedAt: "2026-09-29T16:46:00.000Z", initialHosts: ["payoneer.com"], finalHosts: ["payoneer.com"] },
  { token: "symphony", name: "Symphony Communication Services", admittedAt: "2026-09-29T16:46:00.000Z", initialHosts: ["symphony.com"], finalHosts: ["symphony.com"] },
  { token: "toast", name: "Toast", admittedAt: "2026-09-29T16:46:00.000Z", initialHosts: ["toasttab.com"], finalHosts: ["toasttab.com"] },
  { token: "trillium", name: "Trillium", boardName: "Open Roles", admittedAt: "2026-09-29T16:46:00.000Z", initialHosts: ["trlm.com"], finalHosts: ["trlm.com"] },
  { token: "upstart", name: "Upstart", admittedAt: "2026-09-29T16:46:00.000Z", initialHosts: ["upstart.com"], finalHosts: ["upstart.com"] },
  { token: "workato", name: "Workato", admittedAt: "2026-09-29T16:46:00.000Z", initialHosts: ["workato.com"], finalHosts: ["workato.com"] },
];

export const apiProbedGreenhouseSources: ReviewedGreenhouseSource[] = apiProbedBoards.map((board) => {
  const applicationHosts = [...new Set([...board.initialHosts, ...board.finalHosts])];
  const customHosts = applicationHosts.filter((host) => !host.endsWith('greenhouse.io'));
  const boardName = board.boardName ?? board.name;
  return {
    id: `greenhouse-${board.token}`,
    employerId: board.token,
    displayName: board.name,
    aliases: [board.name],
    boardToken: board.token,
    careersUrl: `https://job-boards.greenhouse.io/${board.token}`,
    expectedBoardNames: [boardName],
    admittedBoardName: boardName,
    admittedAt: board.admittedAt ?? "2026-07-29T21:07:31.798Z",
    allowedInitialHosts: board.initialHosts,
    allowedFinalHosts: board.finalHosts,
    status: 'published',
    evidenceStatus: 'api-probed',
    ...(customHosts.length
      ? { hostExceptionReason: `Fresh Greenhouse probe returned application URLs on ${customHosts.join(', ')}; ownership review is pending.` }
      : {}),
    sourceClass: 'greenhouse',
  };
});
